version: "3.7"

services:
  docker-service-stats:
    container_name: docker-service-stats
    build:
      context: ./docker-service-stats
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www/

  kafka-broker:
    image: confluentinc/cp-kafka:5.0.1
    hostname: kafka-broker
    container_name: kafka-broker
    restart: always
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.40:9091
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.40:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-cluster-network

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - kafka-cluster-network

  # random-logger:
  #   build:
  #     context: ./random-logger
  #     dockerfile: Dockerfile
  #   ports:
  #     - 1234:1234

  clickhouse:
    image: yandex/clickhouse-server:20.4
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "8123::8123"
    # volumes:
      # - /tmp/clickhouse/data:/var/lib/clickhouse
      # - /tmp/clickhouse/log:/var/log/clickhouse-server
      # - /tmp/clickhouse-config.xml:/etc/clickhouse-server/config.xml
    depends_on:
      - zookeeper

  superset:
    image: amancevice/superset:latest
    hostname: superset
    container_name: superset
    ports:
      - "8080:8088"

networks:
  kafka-cluster-network:
    driver: bridge
    name: kafka-cluster-network

volumes:
  appdata:
    driver: local
