version: "3.7"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www/

volumes:
  appdata:
    driver: local
